name: Game request
description: Request to have a game or server added.
title: "Game request: GAME_NAME (SERVER/REGION)"
labels: ["game request"]
body:
  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > You can test your info using the custom game server function.
  - type: input
    attributes:
      label: Game name
    validations:
      required: true
  - type: input
    attributes:
      label: Server region/language
    validations:
      required: true
  - type: input
    attributes:
      description: "Examples: 'JST', 'GMT+9', 'UTC+9', 'Tokyo, Japan', 'Asia/Tokyo'."
      label: Server timezone (location or offset)
    validations:
    required: true
  - type: input
    attributes:
      description: |
        This is usually when you receive daily login rewards. If your game doesn't have login rewards, then this can be when daily missions/tasks/quests reset. 
        This can be the in the server's timezone (preferred), or your own. Whichever is easier for you. If using your own, also include the timezone. If timezone is not mentioned, I will assume it is using the game server's.
      label: Server daily reset time
    validations:
    required: true
  - type: dropdown
    attributes:
      description: |
        (Optional) This question is only applies if the server itself changes timezones during daylight savings. 
        For example, if the reset time is 05:00 during PST and also 05:00 during PDT, you would answer "No". If the reset time changed to 06:00 during PDT, you would answer "Yes".
      label: Does the server reset time change during the server's daylight savings?
      options: 
        - Unsure
        - No
        - Yes
  - type: textarea
    attributes:
      description: Any additional info you want to add.
      label: Anything else?
      placeholder: Optional
  - type: upload
    attributes:
      description: Any additional info you want to add, such as screenshots.
      label: Anything else?
